api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'complejos', views.ComplejoViewSet)
router.register(r'canchas', views.CanchaViewSet, basename='canchas')
router.register(r'reservas', views.ReservaViewSet, basename='reservas')
router.register(r'suscripcion', views.SuscripcionViewSet, basename='suscripciones')

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

app1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('complejo/update', views.complejo_update, name='complejo_update'),
    path('cancha', views.cancha, name='cancha'),
    path('cancha/nueva/', views.cancha_nueva, name='cancha_nueva'),
    path('cancha/<int:pk>/editar/', views.cancha_editar, name='cancha_enlace'),
    path('reserva', views.reserva, name='reserva'),
    path('reserva/<int:pk>/editar/', views.reserva_editar, name='reserva_enlace'),
    path('reserva/nueva/', views.reserva_nueva, name='reserva_nueva'),
    path('reporte_reservas/', views.reporte_reservas, name='reporte_reservas'),
]

futbolito/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='API`S')
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('app1.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name="useraccounts/login.html"), name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
	path('api/', include('api.urls')),
    url(r'^documentacion/', schema_view)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models
from .validators import valid_extension
# Create your models here.

class Complejo (models.Model):
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    nombre_complejo = models.CharField(max_length=40, default='Complejo Deportivo')
    direccion_complejo = models.TextField(max_length=200, default='sector-calle principal-calle secundaria-nro-referencia')
    telefono_complejo = models.CharField(max_length=19, default='(+593) 098-234-1334')
    puntuacion_complejo = models.IntegerField(default='5')
    foto_complejo = models.ImageField(upload_to='images/complejos_images', null=True, blank=True, validators=[valid_extension])
    coordenadas_complejo = models.CharField(max_length=250, null=True, blank=True)
    hora_apertura = models.TimeField(default='09:00')
    hora_cierre = models.TimeField(default='23:00')
    estado_complejo = models.BooleanField(default = True)

    def Publish(self):
        cadena = "{0}"
        return cadena.format(self.nombre_complejo)

    def __str__(self):
        return self.Publish()

class Cancha (models.Model):
    complejo = models.ForeignKey(Complejo, on_delete=models.CASCADE)
    descripcion_cancha = models.CharField(max_length=40, default='Cancha de fútbol Nro 1')
    valor_dia = models.DecimalField(max_digits=7, decimal_places=2)
    valor_noche = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    foto_cancha = models.ImageField(upload_to='images/canchas_images', null=True, blank=True, validators=[valid_extension])
    estado_cancha = models.BooleanField(default = True)

    def Publish(self):
        cadena = "{0}"
        return cadena.format(self.descripcion_cancha)

    def __str__(self):
        return self.Publish()

class Reserva (models.Model):
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    cancha = models.ForeignKey(Cancha, on_delete=models.CASCADE)
    fecha_reserva = models.DateField()
    hora_inicio = models.TimeField(default='12:00')
    hora_fin = models.TimeField(default='13:00')
    valor_unitario = models.DecimalField(max_digits=7, decimal_places=2)
    valor_total = models.DecimalField(max_digits=7, decimal_places=2)
    fecha_creacion = models.DateTimeField(auto_now = True)
    estado_reserva = models.BooleanField(default=True)

    def Publish(self):
        cadena = "{0}, {1}"
        return cadena.format(self.usuario, self.fecha_reserva)

    def __str__(self):
        return self.Publish()


class Suscripcion (models.Model):
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    complejo = models.ForeignKey('Complejo', on_delete=models.CASCADE)
    comentario = models.TextField(max_length=354, null=True)
    puntuacion_usuario = models.IntegerField(default='5')
    fecha_creacion = models.DateTimeField(auto_now = True)
    suscripcion = models.BooleanField(default=False, null=True)

    def Publish(self):
        cadena = "{0}, {1}, {2}"
        return cadena.format(self.usuario, self.puntuacion_usuario, self.comentario )

    def __str__(self):
        return self.Publish()

app1/forms.py
from django import forms

from .models import Cancha, Reserva, Complejo

class ComplejoForm(forms.ModelForm):

    class Meta:
        model = Complejo
        fields = ('nombre_complejo', 'direccion_complejo', 'telefono_complejo', 'foto_complejo', 'coordenadas_complejo', 'hora_apertura', 'hora_cierre')
        widgets = {
            'nombre_complejo': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion_complejo': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono_complejo': forms.TextInput(attrs={'class': 'form-control'}),
            #'foto_complejo': forms.FileInput(attrs={'class': 'form-control'}),
            'coordenadas_complejo': forms.TextInput(attrs={'class': 'form-control'}),
            'hora_apertura': forms.TimeInput(attrs={'class': 'form-control'}),
            'hora_cierre': forms.TimeInput(attrs={'class': 'form-control'}),
        }

class CanchaForm(forms.ModelForm):

    class Meta:
        model = Cancha
        fields = ('descripcion_cancha', 'valor_dia', 'valor_noche', 'foto_cancha', 'estado_cancha')
        widgets = {
        	'descripcion_cancha': forms.TextInput(attrs={'class': 'form-control'}),
        	'valor_dia': forms.NumberInput(attrs={'class': 'form-control'}),
        	'valor_noche': forms.NumberInput(attrs={'class': 'form-control'}),
        #	'foto_cancha': forms.FileInput(attrs={'class': 'form-control'}),
        }

class ReservaForm(forms.ModelForm):

    class Meta:
        model = Reserva
        fields = ('usuario', 'cancha', 'fecha_reserva', 'hora_inicio', 'hora_fin', 'valor_unitario', 'valor_total', 'estado_reserva')

app1/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cancha, Reserva, Complejo, Suscripcion
from .forms import ComplejoForm, CanchaForm, ReservaForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import models
from django.contrib.auth.models import User
from django.http import HttpResponse
import pytz
import datetime
from django.db.models import Q
from django.core.paginator import Paginator
# Create your views here.

#Inicio para realizar login e inicio logueado
def inicio(request):
    usuario = ''
    complejo = ''
    comentarios = ''
    autores = ''
    if(request.user.is_authenticated):
        usuario = request.user
        if (usuario.is_staff == 0) or (usuario.is_superuser == 1):
            return redirect('accounts/logout/')
        complejo = Complejo.objects.get(usuario_id=request.user.id)
        comentarios = list(Suscripcion.objects.filter(complejo_id=complejo))
    return render(request, 'app1/inicio.html', {'usuario': usuario, 'complejo': complejo, 'comentarios': comentarios, 'autores': autores})

#Formulario para actualizar la información del Complejo
@login_required
def complejo_update(request):
    complejo = Complejo.objects.get(usuario_id=request.user.id)
    if request.method == "POST":
        form = ComplejoForm(request.POST, request.FILES, instance=complejo)
        if form.is_valid():
            complejo = form.save(commit=False)
            complejo.save()
            return redirect('inicio')
    else:
        form = ComplejoForm(instance=complejo)
    return render(request, 'app1/complejo_editar.html', {'titulo': 'Editar información del Complejo', 'form': form})

#Listado de canchas del complejo
@login_required
def cancha(request):
    id_comple = Complejo.objects.get(usuario_id=request.user.id)
    canchas = list(Cancha.objects.filter(complejo_id=id_comple))
    return render(request, 'app1/cancha.html', {'titulo': 'Listado de canchas', 'canchas': canchas})

#Formulario para ingresar una nueva cancha al complejo
@login_required
def cancha_nueva(request):
    if request.method == "POST":
        form = CanchaForm(request.POST, request.FILES)
        if form.is_valid():
            cancha = form.save(commit=False)
            id_comple = Complejo.objects.get(usuario_id=request.user.id)
            cancha.complejo = id_comple
            cancha.fecha_creacion = timezone.now()
            cancha.save()
            messages.success(request, '¡ Cancha guardada con éxito !')
            return redirect('cancha')
    else:
        form = CanchaForm()
    return render(request, 'app1/cancha_editar.html', {'titulo': 'Agregar cancha', 'form': form})

#Formulario para editar la información de una cancha existente
@login_required
def cancha_editar(request, pk):
    cancha = get_object_or_404(Cancha, pk=pk)
    if request.method == "POST":
        form = CanchaForm(request.POST, request.FILES, instance=cancha)
        if form.is_valid():
            cancha = form.save(commit=False)
            cancha.fecha_creacion = timezone.now()
            #cancha.foto_cancha = request.FILES.get('foto_cancha')
            cancha.save()
            messages.success(request, '¡ Cancha modificada con éxito !')
            return redirect('cancha')
    else:
        id_comple = Complejo.objects.get(usuario_id=request.user.id)
        canchas = list(Cancha.objects.filter(complejo_id=id_comple))
        cancha_encontrada = False
        for cancha_act in canchas:
            if cancha == cancha_act:
                cancha_encontrada = True
        if cancha_encontrada == False:
            messages.error(request, '¡ No tiene acceso a ese enlace !')
            return redirect('cancha')
        form = CanchaForm(instance=cancha)
    return render(request, 'app1/cancha_editar.html', {'titulo': 'Editar cancha', 'form': form})

#Listado de reservas activas del Compplejo
@login_required
def reserva(request):
    id_comple = Complejo.objects.get(usuario_id=request.user.id)
    canchas = list(Cancha.objects.filter(complejo_id=id_comple))
    reservas = Reserva.objects.filter(cancha_id__in=canchas, estado_reserva=1).order_by('fecha_reserva', 'hora_inicio')

    #Actualización del estado de reservas (Cancelación de reservas vencidas)
    ecuador = pytz.timezone('America/Guayaquil')
    fecha_hoy = datetime.datetime.now(ecuador)
    hora_actual = fecha_hoy.strftime("%H:%M")
    hora_actual = datetime.datetime.strptime(hora_actual, "%H:%M").time()
    fecha_hoy = fecha_hoy.strftime("%Y-%m-%d")
    fecha_hoy = datetime.datetime.strptime(fecha_hoy, "%Y-%m-%d").date()

    actualizacionReservas = []
    for reserva_act in reservas:
        if(reserva_act.fecha_reserva < fecha_hoy):
            Reserva.objects.filter(id=reserva_act.id).update(estado_reserva=0)
        else:
            actualizacionReservas.append(reserva_act)
    return render(request, 'app1/reserva.html', {'titulo': 'Listado de reservas activas', 'reservas': actualizacionReservas})

#Formulario para agregar una nueva reserva
@login_required
def reserva_nueva(request):
    id_comple = Complejo.objects.get(usuario_id=request.user.id) #Obtener el complejo que le pertenece al administador logueado
    canchas = list(Cancha.objects.filter(complejo_id=id_comple)) #Obtener las canchas que le pertenecen a ese complejo
    reservas = Reserva.objects.filter(cancha_id__in=canchas, estado_reserva=1)

    if request.method == "POST": #Si se envia datos del formulario:
    	form = ReservaForm(request.POST)
    	if form.is_valid(): #Si el formulario es válido:
            reserva = form.save(commit=False) #Los datos enviados no se guardan aún
            #Control para el input de usuario:
            user_ing = User.objects.get(id=reserva.usuario.id) #Se obtiene el usuario ingresado
            if user_ing.is_staff == 1: #Si el usuario ingresado es staff:
                messages.error(request, 'El usuario ingresado no puede realizar reservas')
                return redirect('reserva')
            #Control para el input de fecha:
            ecuador = pytz.timezone('America/Guayaquil')
            fecha_ac = datetime.datetime.now(ecuador)
            fecha_ac = fecha_ac.strftime("%Y-%m-%d")
            fecha_ac = datetime.datetime.strptime(fecha_ac, "%Y-%m-%d").date()
            fecha_sup = datetime.datetime.strptime("2019-12-31", "%Y-%m-%d").date()
            if (reserva.fecha_reserva < fecha_ac) or (reserva.fecha_reserva > fecha_sup):
                messages.error(request, 'La fecha ingresada no es válida')
                return redirect('reserva')
            #Control para el input de horas (hora_inicio y hora_fin):
            if reserva.hora_inicio > reserva.hora_fin:
                messages.error(request, 'La hora ingresada no es válida')
                return redirect('reserva')
            mint_hi = reserva.hora_inicio.strftime("%H:%M")
            mint_hi = mint_hi[3:]
            mint_hi = int(mint_hi)
            mint_hf = reserva.hora_fin.strftime("%H:%M")
            mint_hf = mint_hf[3:]
            mint_hf = int(mint_hf)
            if (mint_hi != 0 and mint_hi != 30) or (mint_hf != 0 and mint_hf != 30):
                messages.error(request, 'La hora ingresada no es válida')
                return redirect('reserva')
            compr = 0
            for cancha in canchas:
                if reserva.cancha_id == cancha.id:
                    compr = 1
            if compr == 1:
                for reserv in reservas:
                    if reserv.cancha_id == reserva.cancha_id and reserv.fecha_reserva == reserva.fecha_reserva and reserv.hora_inicio == reserva.hora_inicio and reserv.hora_fin == reserva.hora_fin:
                        messages.error(request, 'La cancha está ocupada')
                        return redirect('reserva')
                    elif reserv.cancha_id == reserva.cancha_id and reserv.fecha_reserva == reserva.fecha_reserva and ((reserva.hora_inicio > reserv.hora_inicio and reserva.hora_inicio < reserv.hora_fin) or (reserva.hora_fin > reserv.hora_inicio and reserva.hora_fin < reserv.hora_fin) or (reserva.hora_inicio == reserv.hora_inicio or reserva.hora_fin == reserv.hora_fin) or (reserva.hora_inicio < reserv.hora_inicio and reserva.hora_fin > reserv.hora_fin)):
                        messages.error(request, 'La cancha está ocupada')
                        return redirect('reserva')
                reserva.fecha_creacion = timezone.now()
                reserva.save()
                messages.success(request, '¡ Reserva guardada con éxito !')
                return redirect('reserva')
            else:
                messages.error(request, 'Este cancha no pertenece al complejo')
                return redirect('reserva')
    else:
        id_comple = Complejo.objects.get(usuario_id=request.user.id)
        canchas = list(Cancha.objects.filter(complejo_id=id_comple, estado_cancha=1))
        usuarios_suscritos = Suscripcion.objects.filter(complejo_id=id_comple, suscripcion=1)
        suscritos = []
        for usuario_suscrito in usuarios_suscritos:
            suscritos.append(usuario_suscrito.usuario_id)
        Usuario_final = User.objects.get(username='Usuario_final')
        suscritos.append(Usuario_final.id)
        usuarios = User.objects.filter(is_staff=0, id__in=suscritos)
        form = ReservaForm()
    return render(request, 'app1/reserva_editar.html', {'titulo': 'Agregar reserva', 'form': form, 'canchas': canchas, 'usuarios': usuarios, 'complejo': id_comple})

#Formulario para cancelar la reserva
@login_required
def reserva_editar(request, pk):
    reserva = get_object_or_404(Reserva, pk=pk)
    if request.method == "POST":
        Reserva.objects.filter(id=pk).delete()
        messages.success(request, '¡ Reserva cancelada !')
        return redirect('reserva')
    else:
        ecuador = pytz.timezone('America/Guayaquil')
        fecha_hoy = datetime.datetime.now(ecuador)

app1/templates/app1/cancha.html
{% extends 'app1/base.html' %}
{% block content %}
<section id="call-to-action">
    {% if messages %}
    <div class="row">
      <div class="col-sm-12">
        {% for message in messages %}
        <p {% if message.tags == "success" %} class="alert alert-success" {% else %} class="alert alert-danger"
          {% endif %}>{{ message }}
        </p>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    <div>
      <h1>{{ titulo }}</h1>
      <a href="{% url 'cancha_nueva' %}" class="btn btn-primary"><span class="glyphicon glyphicon-plus">AÑADIR NUEVA CANCHA</span></a>
    </div>
  <div class="table-responsive">
      <table class="table table-striped table-dark">
        <!-- <caption style="color: #f8f9fa"></caption> -->
        <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Decripción</th>
            <th scope="col">Valor de día</th>
            <th scope="col">Valor de noche</th>
            <th scope="col">Estado</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for cancha in canchas %}
          <tr>
            <td>0000{{ cancha.id }}</td>
            <td><a title="Modificar cancha" href="{% url 'cancha_enlace' pk=cancha.pk %}">{{ cancha.descripcion_cancha }}</a></td>
            <td>{{ cancha.valor_dia }}</td>
            <td>{{ cancha.valor_noche }}</td>
            <td> 
            {% if cancha.estado_cancha %} 
              Activa
            {%else%}
              Inactiva
            {%endif%}
          </td>
            <td><a href="{% url 'cancha_enlace' pk=cancha.pk %}" class="btn btn-secondary">MODIFICAR</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
</section>
{% endblock %}

app1/templates/app1/complejo_editar.html
{% extends 'app1/base.html' %}

{% block content %}
<section id="call-to-action">
    <div class="container">

	<h1>{{ titulo }}</h1>
    	<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
			<div class="form-row">
                <div class="form-group col-md-3">
                    <label for="nombre_complejo">Nombre:</label>
                    {{ form.nombre_complejo }}
				</div>
            </div>
            <div class="form-row">
				<div class="form-group col-md-5">
                    <label for="direccion_complejo">Dirección:</label>
                    {{ form.direccion_complejo }}
				</div>
            </div>
             <div class="form-row">
                <div class="form-group col-md-2">
                    <label for="valor_noche">Teléfono:</label>
                    {{ form.telefono_complejo }}
                </div>
                <div class="form-group col-md-6">
                    <label for="coordenadas_complejo">Coordenadas:</label>
                    {{ form.coordenadas_complejo }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label for="hora_apertura">Hora apertura:</label>
                    {{ form.hora_apertura }}
                </div>
                <div class="form-group col-md-2">
                    <label for="hora_cierre">Hora cierre:</label>
                    {{ form.hora_cierre }}
                </div>
            </div>
            <div class="form-row">
				<div class="form-group col-md-5">
                    <label for="foto_cancha">Foto:</label>
                    {{ form.foto_complejo }}
                </div>
             </div>
        	<input class="btn btn-primary" type="submit" value="Guardar">

    	</form>
</div>
</section>
{% endblock %}

app1/templates/app1/reserva_editar.html
{% extends 'app1/base.html' %}

{% block content %}
<section id="call-to-action" style="color: white">
        <h1>{{ titulo }}</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_usuario">Usuario:</label>
                    <select name="usuario" required id="usuario_id" class="form-control">
                        <option value="" selected>seleccione...</option>
                        {% for usuario in usuarios %}
                        <option value="{{ usuario.id }}">{{ usuario.username }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group col-md-6">
                    <label for="id_cancha">Cancha:</label>
                    <select name="cancha" required id="id_cancha" class="form-control">
                        <option value="" selected>seleccione...</option>
                        {% for cancha in canchas %}
                        <option value="{{ cancha.id }}">{{ cancha.descripcion_cancha }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group col-md-6">
                    <label for="id_fecha_reserva">Fecha a reservar:</label>
                    <input name="fecha_reserva" required="" id="id_fecha_reserva" type="date" max="2019-12-31" class="form-control">
                </div>

                <div class="form-group col-md-3">
                    <label for="id_hora_inicio">Hora inicio:</label>
                    <input type="time" name="hora_inicio" value="12:00" step="1800" required id="id_hora_inicio"
                        class="form-control">
                </div>
                <div class="form-group col-md-3">
                    <label for="id_hora_fin">Hora fin:</label>
                    <input type="time" name="hora_fin" step="1800" required id="id_hora_fin" class="form-control">
                </div>
                <div class="form-group col-md-2">
                    <label for="id_valor_unitario">Valor unitario:</label>
                    <input class="form-control" type="number" name="valor_unitario" step="0.01" required
                        id="id_valor_unitario" readonly="true" class="form-control">
                </div>
                <div class="form-group col-md-2">
                    <label for="id_valor_total">Valor total:</label>
                    <input class="form-control" type="number" name="valor_total" step="0.01" required
                        id="id_valor_total" readonly="true" class="form-control">
                </div>
                <div class="form-group col-md-1">
                    <label for="estado_reserva">Estado:</label><br>
                    {{ form.estado_reserva }}
                </div>
            </div>
            <input class="btn btn-primary btn-lg" type="submit" value="Guardar" class="form-control">
        </form>
</section>

        <script>
                function calcularHoraActual(){
                    var f = new Date();
                    var yyyy = f.getFullYear();
                    var mm = f.getMonth()+1;
                    var dd = f.getDate();
                    var hh = f.getHours();
                    var min = f.getMinutes();
                    var ss = f.getSeconds();
                    if(dd<10) {
                        dd='0'+dd
                    }
                    if(mm<10) {
                        mm='0'+mm
                    }
                    f = yyyy+'-'+mm+'-'+dd;
                    $("#id_fecha_reserva").attr("min", f);
                    var fecha_ing = $("#id_fecha_reserva").val();
                    if (fecha_ing == f){
                        if (min<=30){
                            h = hh+':'+30;
                        } else {
                            hh = hh+1
                            h = hh+':'+'00';
                        }
                        if(hh<10){
                          h = '0'+h;
                        }
                        hh = h.substr(0, 2);
                        var hora_ap = "{{ complejo.hora_apertura }}";
                        hora_ap = hora_ap.substr(0, 2);
                        hora_ap = parseFloat(hora_ap);
                        if( hh < hora_ap ) {
                            $("#id_hora_inicio").attr("value", "{{ complejo.hora_apertura }}");
                            $("#id_hora_inicio").attr("min", "{{ complejo.hora_apertura }}");
                        } else {
                            $("#id_hora_inicio").attr("value", h);
                            $("#id_hora_inicio").attr("min", h);
                        }
                    } else {
                        $("#id_hora_inicio").attr("value", "{{ complejo.hora_apertura }}");
                        $("#id_hora_inicio").attr("min", "{{ complejo.hora_apertura }}");
                    }

                }
                function cambiarHoraFin(){
                    var h_fin = $("#id_hora_inicio").val();
                    var hh_fin = h_fin.substr(0, 2);
                    var min_fin = h_fin.substr(3, 5);
                    hh_fin = parseFloat(hh_fin);
                    hh_fin = hh_fin + 1;
                    if(hh_fin<10){
                        hh_fin='0'+hh_fin
                    }
                    h_fin = hh_fin+':'+min_fin;
                    $("#id_hora_fin").attr("value", h_fin/*Hora q cierra el comlejo*/);
                    $("#id_hora_fin").attr("min", h_fin);
                    $("#id_hora_fin").attr("max", "{{ complejo.hora_cierre }}");
                }

                function determinarValorUnitario(){
                    var cancha_select = $("#id_cancha").val();
                    var hora_fin = $("#id_hora_fin").val();
                    var v_unitario = 0;
                    {% for cancha in canchas %}
                        if (cancha_select == {{ cancha.id }}) {
                            v_unitario = {{ cancha.valor_dia }}
                            if (hora_fin >= '19:00') {
                                v_unitario = {{ cancha.valor_noche }}
                            }
                        }
                        if (v_unitario == 0){
                            v_unitario = {{ cancha.valor_dia }}
                        }
                        $("#id_valor_unitario").val(v_unitario);
                    {% endfor %}
                    calcularValorTotal();
                }

                function calcularValorTotal(){
                    var valor_unitario = $("#id_valor_unitario").val();
                    var valor_total = 0;

                    var hora_inicio = $("#id_hora_inicio").val();
                    var hh_inicio = hora_inicio.substr(0, 2);
                    var min_inicio = hora_inicio.substr(3, 5);
                    hh_inicio = parseFloat(hh_inicio);
                    min_inicio = parseFloat(min_inicio);

                    var hora_fin = $("#id_hora_fin").val();
                    var hh_fin = hora_fin.substr(0, 2);
                    var min_fin = hora_fin.substr(3, 5);
                    hh_fin = parseFloat(hh_fin);
                    min_fin = parseFloat(min_fin);

                    var nro_horas = hh_fin - hh_inicio;
                    var nro_minutos = min_fin - min_inicio;
                    var valor_min = 0;

                    if (nro_minutos == 0) {
                        valor_total = valor_unitario * nro_horas;
                    } else {
                        if (nro_minutos == -30) {
                            valor_min = valor_unitario * 0.5;
                            valor_total = (valor_unitario * (nro_horas-1)) + valor_min;
                        } else {
                            valor_min = valor_unitario * 0.5;
                            valor_total = (valor_unitario * nro_horas) + valor_min;
                        }
                    }
                    $("#id_valor_total").val(valor_total);
                }


            $(document).ready(function(){
                calcularHoraActual();
                cambiarHoraFin();
            });

            $("#id_fecha_reserva").keyup(function () {
                calcularHoraActual();
                cambiarHoraFin();
            });
            $("#id_fecha_reserva").change(function () {
                calcularHoraActual();
                cambiarHoraFin();
            });

            $("#id_hora_inicio").keyup(function () {
                cambiarHoraFin();
                determinarValorUnitario();
            });
            $("#id_hora_inicio").change(function () {
                cambiarHoraFin();
                determinarValorUnitario();
            });

            $("#id_hora_fin").keyup(function () {
                determinarValorUnitario();
            });
            $("#id_hora_fin").change(function () {
                determinarValorUnitario();
            });


            $("#id_cancha").keyup(function () {
                determinarValorUnitario();
            });
            $("#id_cancha").change(function () {
                determinarValorUnitario();
            });


            </script>
{% endblock %}

app1/templates/app1/update_Complejo.html
{%extends 'app1/template_Complejo.html'%}
{% block title %} Actualizar Complejo {% endblock %}
{% block fragmentos %}
<form method="post">
  {% csrf_token%}
  {{ form.as_p}}
  <button type="submit" name="button">Actualizar</button>
</form>
{% endblock %}